/**
 * Nashik Startup & Company Directory
 * ------------------------------------------------------------------
 * Curated, public-information-only list of startups, businesses, and
 * companies operating in Nashik. Intended for Nashik students and
 * job-seekers to discover local opportunities.
 *
 * Coordinates are approximate (city / area centroid). Website/contact
 * fields are empty strings when not publicly available.
 */
export const NASHIK_COMPANIES = [
  // ========================= SOFTWARE / IT / SaaS =========================
  {
    id: "winjit-technologies",
    name: "Winjit Technologies",
    type: "company",
    sector: "Software / IT",
    stage: "Established",
    area: "Gangapur Road",
    address: "Gangapur Road, Nashik",
    lat: 19.9975,
    lng: 73.7898,
    description:
      "AI/ML, IoT, and digital transformation engineering services; one of Nashik's largest product companies.",
    website: "https://www.winjit.com/",
    hiring: true,
    size: "500+",
    roles: ["Software Engineer", "ML Engineer", "QA", "DevOps"],
    founded: 2008,
  },
  {
    id: "winjit-ai",
    name: "Winjit AI Labs",
    type: "company",
    sector: "AI / ML",
    stage: "Established",
    area: "Gangapur Road",
    address: "Gangapur Road, Nashik",
    lat: 19.9975,
    lng: 73.7898,
    description: "AI research and applied AI product team within Winjit.",
    website: "https://www.winjit.com/ai-ml/",
    hiring: true,
    size: "50+",
    roles: ["ML Engineer", "Data Scientist", "Python Developer"],
    founded: 2019,
  },
  {
    id: "thinkitive-technologies",
    name: "Thinkitive Technologies",
    type: "company",
    sector: "Software / IT",
    stage: "Established",
    area: "College Road",
    address: "College Road, Nashik",
    lat: 20.0055,
    lng: 73.7844,
    description:
      "Custom software development — web, mobile, cloud, and product engineering.",
    website: "https://www.thinkitive.com/",
    hiring: true,
    size: "200+",
    roles: ["Full-Stack Developer", "React Developer", "Node.js Developer"],
    founded: 2012,
  },
  {
    id: "shrinika-technologies",
    name: "Shrinika Technologies",
    type: "company",
    sector: "Software / IT",
    stage: "Established",
    area: "Satpur",
    address: "Satpur MIDC, Nashik",
    lat: 19.9972,
    lng: 73.7346,
    description: "IT services and consulting with focus on enterprise apps.",
    website: "",
    hiring: true,
    size: "50+",
    roles: ["Java Developer", "Salesforce Developer"],
    founded: 2014,
  },
  {
    id: "sagenext-infotech",
    name: "Sagenext Infotech",
    type: "startup",
    sector: "SaaS",
    stage: "Bootstrapped",
    area: "Nashik Road",
    address: "Nashik Road, Nashik",
    lat: 19.9457,
    lng: 73.8426,
    description: "Cloud hosting and QuickBooks/Xero hosting provider.",
    website: "https://www.sagenext.com/",
    hiring: true,
    size: "50+",
    roles: ["Cloud Engineer", "Support Engineer"],
    founded: 2009,
  },
  {
    id: "myboutique-technologies",
    name: "MyBoutique Technologies",
    type: "startup",
    sector: "Software / IT",
    stage: "Bootstrapped",
    area: "Dwarka",
    address: "Dwarka, Nashik",
    lat: 20.0118,
    lng: 73.7756,
    description: "Custom software & digital agency for SMBs and startups.",
    website: "",
    hiring: true,
    size: "20+",
    roles: ["Web Developer", "Designer"],
    founded: 2016,
  },
  {
    id: "zenfri-technologies",
    name: "ZenFRI Technologies",
    type: "startup",
    sector: "Software / IT",
    stage: "Bootstrapped",
    area: "Panchavati",
    address: "Panchavati, Nashik",
    lat: 20.0245,
    lng: 73.7932,
    description: "Mobile and web product development studio.",
    website: "",
    hiring: false,
    size: "10+",
    roles: ["Mobile Developer", "Backend Developer"],
    founded: 2018,
  },
  {
    id: "codetribe-software",
    name: "CodeTribe Software",
    type: "startup",
    sector: "Edtech",
    stage: "Pre-seed",
    area: "College Road",
    address: "College Road, Nashik",
    lat: 20.0055,
    lng: 73.7844,
    description: "Coding bootcamps and college training programs.",
    website: "",
    hiring: true,
    size: "10+",
    roles: ["Teaching Assistant", "Curriculum Engineer"],
    founded: 2021,
  },

  // ========================= MANUFACTURING / INDUSTRIAL =========================
  {
    id: "siemens-nashik",
    name: "Siemens Limited",
    type: "company",
    sector: "Manufacturing",
    stage: "Public",
    area: "Satpur",
    address: "Satpur MIDC, Nashik",
    lat: 19.9972,
    lng: 73.7346,
    description: "Industrial automation, switchgear, motors, and drives plant.",
    website: "https://www.siemens.com/in/en.html",
    hiring: true,
    size: "1000+",
    roles: ["GET", "Design Engineer", "Production Engineer"],
    founded: 1922,
  },
  {
    id: "schneider-electric",
    name: "Schneider Electric",
    type: "company",
    sector: "Manufacturing",
    stage: "Public",
    area: "Satpur",
    address: "Satpur MIDC, Nashik",
    lat: 19.9972,
    lng: 73.7346,
    description: "Power distribution and electrical equipment manufacturing.",
    website: "https://www.se.com/in/en/",
    hiring: true,
    size: "500+",
    roles: ["Embedded Engineer", "Quality Engineer"],
    founded: 1836,
  },
  {
    id: "abb-nashik",
    name: "ABB India",
    type: "company",
    sector: "Manufacturing",
    stage: "Public",
    area: "Satpur",
    address: "Satpur MIDC, Nashik",
    lat: 19.9972,
    lng: 73.7346,
    description: "Electrification, motion, and process automation products.",
    website: "https://new.abb.com/in",
    hiring: true,
    size: "1000+",
    roles: ["R&D Engineer", "Power Systems"],
    founded: 1988,
  },
  {
    id: "bosch-nashik",
    name: "Bosch Limited",
    type: "company",
    sector: "Manufacturing",
    stage: "Public",
    area: "Satpur",
    address: "Satpur MIDC, Nashik",
    lat: 19.9972,
    lng: 73.7346,
    description: "Automotive technology, power tools, and industrial solutions.",
    website: "https://www.bosch.in/",
    hiring: true,
    size: "500+",
    roles: ["Mechanical Engineer", "Production Engineer"],
    founded: 1951,
  },
  {
    id: "mahindra-nashik",
    name: "Mahindra & Mahindra",
    type: "company",
    sector: "Automotive",
    stage: "Public",
    area: "Igatpuri",
    address: "Igatpuri Plant, Nashik",
    lat: 19.6973,
    lng: 73.5605,
    description: "SUV and tractor manufacturing facility.",
    website: "https://www.mahindra.com/",
    hiring: true,
    size: "1000+",
    roles: ["GET", "Quality Engineer", "Manufacturing Engineer"],
    founded: 1945,
  },
  {
    id: "ceat-nashik",
    name: "CEAT Limited",
    type: "company",
    sector: "Manufacturing",
    stage: "Public",
    area: "Vilholi",
    address: "Vilholi, Nashik",
    lat: 19.9458,
    lng: 73.6819,
    description: "Tyre manufacturing plant.",
    website: "https://www.ceat.com/",
    hiring: true,
    size: "500+",
    roles: ["Mechanical Engineer", "Production Engineer"],
    founded: 1958,
  },
  {
    id: "glide-labs",
    name: "Glide Laboratories",
    type: "company",
    sector: "Pharma",
    stage: "Established",
    area: "Satpur",
    address: "Satpur MIDC, Nashik",
    lat: 19.9972,
    lng: 73.7346,
    description: "Pharmaceutical formulations manufacturer.",
    website: "",
    hiring: true,
    size: "200+",
    roles: ["QA / QC", "Production Chemist"],
    founded: 1984,
  },

  // ========================= FOOD / AGRI / D2C =========================
  {
    id: "sula-vineyards",
    name: "Sula Vineyards",
    type: "company",
    sector: "Food & Beverage",
    stage: "Public",
    area: "Gangapur",
    address: "Gangapur, Nashik",
    lat: 20.0153,
    lng: 73.7045,
    description: "India's largest wine producer — vineyard tours, hospitality, exports.",
    website: "https://www.sulavineyards.com/",
    hiring: true,
    size: "500+",
    roles: ["Hospitality", "Vineyard Operations", "Marketing"],
    founded: 1999,
  },
  {
    id: "york-wineries",
    name: "York Winery",
    type: "company",
    sector: "Food & Beverage",
    stage: "Established",
    area: "Gangapur",
    address: "Gangapur, Nashik",
    lat: 20.0153,
    lng: 73.7045,
    description: "Premium wine producer with tasting rooms and stays.",
    website: "https://yorkwinery.com/",
    hiring: false,
    size: "50+",
    roles: ["Hospitality"],
    founded: 2005,
  },
  {
    id: "grover-zampa",
    name: "Grover Zampa Vineyards",
    type: "company",
    sector: "Food & Beverage",
    stage: "Established",
    area: "Gangapur",
    address: "Gangapur, Nashik",
    lat: 20.0153,
    lng: 73.7045,
    description: "Heritage winery producing premium Indian wines.",
    website: "https://www.groverzampa.in/",
    hiring: false,
    size: "100+",
    roles: ["Operations"],
    founded: 1992,
  },
  {
    id: "krushikaka-agri",
    name: "KrushiKaka Agritech",
    type: "startup",
    sector: "AgriTech",
    stage: "Seed",
    area: "Nashik Road",
    address: "Nashik Road, Nashik",
    lat: 19.9457,
    lng: 73.8426,
    description: "Digital marketplace and advisory for onion & grape farmers.",
    website: "",
    hiring: true,
    size: "10+",
    roles: ["Full-Stack Developer", "Agronomist"],
    founded: 2022,
  },

  // ========================= HEALTH / BIOTECH =========================
  {
    id: "kashibio",
    name: "KashiBio",
    type: "startup",
    sector: "Healthtech",
    stage: "Seed",
    area: "College Road",
    address: "College Road, Nashik",
    lat: 20.0055,
    lng: 73.7844,
    description: "Biotech tools and diagnostics for rural labs.",
    website: "",
    hiring: true,
    size: "10+",
    roles: ["Biotech Engineer", "Data Analyst"],
    founded: 2021,
  },

  // ========================= LOGISTICS / SERVICES =========================
  {
    id: "shakti-logistics",
    name: "Shakti Logistics",
    type: "company",
    sector: "Logistics",
    stage: "Established",
    area: "Dwarka",
    address: "Dwarka, Nashik",
    lat: 20.0118,
    lng: 73.7756,
    description: "Road freight, supply-chain services across Maharashtra.",
    website: "",
    hiring: true,
    size: "100+",
    roles: ["Operations Executive", "Driver"],
    founded: 2008,
  },

  // ========================= MEDIA / AGENCY / CREATIVE =========================
  {
    id: "pixelloid-creations",
    name: "Pixelloid Creations",
    type: "company",
    sector: "Media / VFX",
    stage: "Established",
    area: "Gangapur Road",
    address: "Gangapur Road, Nashik",
    lat: 19.9975,
    lng: 73.7898,
    description: "VFX and CGI studio working on films, ads, and games.",
    website: "",
    hiring: true,
    size: "50+",
    roles: ["3D Artist", "Compositor", "VFX Supervisor"],
    founded: 2009,
  },
  {
    id: "studio-ninetyone",
    name: "Studio NinetyOne",
    type: "startup",
    sector: "Creative Agency",
    stage: "Bootstrapped",
    area: "College Road",
    address: "College Road, Nashik",
    lat: 20.0055,
    lng: 73.7844,
    description: "Branding, web design, and social media agency.",
    website: "",
    hiring: true,
    size: "10+",
    roles: ["Designer", "Social Media Manager"],
    founded: 2019,
  },

  // ========================= FINTECH / EDTECH =========================
  {
    id: "nashik-finserv",
    name: "Nashik Finserv",
    type: "startup",
    sector: "Fintech",
    stage: "Pre-seed",
    area: "Gangapur Road",
    address: "Gangapur Road, Nashik",
    lat: 19.9975,
    lng: 73.7898,
    description: "Micro-lending and savings platform for shopkeepers.",
    website: "",
    hiring: true,
    size: "10+",
    roles: ["Full-Stack Developer", "Credit Analyst"],
    founded: 2023,
  },
  {
    id: "vidyarambh-edutech",
    name: "Vidyarambh EduTech",
    type: "startup",
    sector: "Edtech",
    stage: "Seed",
    area: "Nashik Road",
    address: "Nashik Road, Nashik",
    lat: 19.9457,
    lng: 73.8426,
    description: "Vernacular K-12 tutoring marketplace for rural Maharashtra.",
    website: "",
    hiring: true,
    size: "20+",
    roles: ["Content Writer", "Frontend Developer"],
    founded: 2020,
  },

  // ========================= INCUBATORS / ACCELERATORS =========================
  {
    id: "ciie-iccs-nashik",
    name: "CIIE — ICCS Nashik",
    type: "company",
    sector: "Incubator",
    stage: "Established",
    area: "Gangapur Road",
    address: "Gangapur Road, Nashik",
    lat: 19.9975,
    lng: 73.7898,
    description:
      "Centre for Innovation, Incubation & Entrepreneurship — startup support, mentorship, funding.",
    website: "",
    hiring: false,
    size: "10+",
    roles: ["Incubation Manager"],
    founded: 2018,
  },
  {
    id: "startup-nashik",
    name: "Startup Nashik (Community)",
    type: "startup",
    sector: "Community",
    stage: "Bootstrapped",
    area: "Gangapur Road",
    address: "Gangapur Road, Nashik",
    lat: 19.9975,
    lng: 73.7898,
    description:
      "Founder-led community hosting meetups, demo days, and founder networking across Nashik.",
    website: "",
    hiring: false,
    size: "1-10",
    roles: ["Volunteer", "Community Manager"],
    founded: 2019,
  },
];

/* ---------------- helpers ---------------- */

export const SECTORS = [
  "Software / IT",
  "AI / ML",
  "SaaS",
  "Edtech",
  "Manufacturing",
  "Automotive",
  "Pharma",
  "Food & Beverage",
  "AgriTech",
  "Healthtech",
  "Logistics",
  "Media / VFX",
  "Creative Agency",
  "Fintech",
  "Incubator",
  "Community",
];

export const STAGES = [
  "Pre-seed",
  "Seed",
  "Bootstrapped",
  "Established",
  "Series A",
  "Public",
];

export const TYPES = ["startup", "company"];

export const AREAS = [
  "Gangapur Road",
  "Gangapur",
  "Satpur",
  "College Road",
  "Dwarka",
  "Panchavati",
  "Nashik Road",
  "Vilholi",
  "Igatpuri",
];